import {
  CODE_INTERPRETER_TOOL_PARAMETERS,
  COMPUTER_TOOL_PARAMETERS,
  EMPTY_UNSAFE_TOOL_PARAMETERS,
  FILE_SEARCH_TOOL_PARAMETERS,
  IMAGE_GENERATION_TOOL_PARAMETERS,
  TOOL_SEARCH_TOOL_PARAMETERS,
  WEB_SEARCH_TOOL_PARAMETERS,
} from './schemas.js';
import type {
  CodexProviderBuiltinToolDefinition,
  CodexProviderBuiltinToolName,
} from './types.js';

export const CODEX_PROVIDER_BUILTIN_TOOL_DEFINITIONS: Record<
  CodexProviderBuiltinToolName,
  CodexProviderBuiltinToolDefinition
> = {
  web_search: {
    name: 'web_search',
    openaiToolTypes: ['web_search'],
    toolModes: ['provider-native', 'adapter-emulated'],
    adapterEmulatedSupported: true,
    providerNativeSupported: true,
    requiresExecutor: true,
    unsafeByDefault: false,
    defaultEmulatedToolName: 'web_search',
    description: 'Search the web for current information and return concise cited results.',
    parameters: WEB_SEARCH_TOOL_PARAMETERS,
    status: 'partial',
  },
  file_search: {
    name: 'file_search',
    openaiToolTypes: ['file_search'],
    toolModes: ['adapter-emulated'],
    adapterEmulatedSupported: true,
    providerNativeSupported: false,
    requiresExecutor: true,
    unsafeByDefault: false,
    defaultEmulatedToolName: 'file_search',
    description: 'Search explicitly configured file-search sources and return OpenAI-compatible file chunks.',
    parameters: FILE_SEARCH_TOOL_PARAMETERS,
    status: 'supported',
  },
  tool_search: {
    name: 'tool_search',
    openaiToolTypes: ['tool_search'],
    toolModes: ['adapter-emulated'],
    adapterEmulatedSupported: true,
    providerNativeSupported: false,
    requiresExecutor: true,
    unsafeByDefault: false,
    defaultEmulatedToolName: 'adapter_tool_search',
    description: 'Discover deferred tool definitions and expose them to the next provider model turn.',
    parameters: TOOL_SEARCH_TOOL_PARAMETERS,
    status: 'partial',
  },
  mcp: {
    name: 'mcp',
    openaiToolTypes: ['mcp'],
    toolModes: ['provider-native', 'codex-local-first'],
    adapterEmulatedSupported: false,
    providerNativeSupported: true,
    requiresExecutor: true,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_mcp',
    description: 'Remote MCP / connector access. Keep provider-native or Codex-local unless a host supplies an explicit adapter.',
    parameters: EMPTY_UNSAFE_TOOL_PARAMETERS,
    status: 'planned',
  },
  skill: {
    name: 'skill',
    openaiToolTypes: ['skill'],
    toolModes: ['codex-local-first'],
    adapterEmulatedSupported: false,
    providerNativeSupported: false,
    requiresExecutor: false,
    unsafeByDefault: false,
    defaultEmulatedToolName: 'adapter_skill',
    description: 'Codex-local skill surface. Not an OpenAI Responses hosted tool.',
    parameters: EMPTY_UNSAFE_TOOL_PARAMETERS,
    status: 'local-first',
  },
  shell: {
    name: 'shell',
    openaiToolTypes: ['shell'],
    toolModes: ['codex-local-first'],
    adapterEmulatedSupported: false,
    providerNativeSupported: false,
    requiresExecutor: true,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_shell',
    description: 'Unsafe shell execution surface. Must stay Codex-local unless a host explicitly binds a safe executor.',
    parameters: EMPTY_UNSAFE_TOOL_PARAMETERS,
    status: 'local-first',
  },
  local_shell: {
    name: 'local_shell',
    openaiToolTypes: ['local_shell'],
    toolModes: ['codex-local-first'],
    adapterEmulatedSupported: false,
    providerNativeSupported: false,
    requiresExecutor: true,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_local_shell',
    description: 'Codex-local shell tool. Adapter execution is intentionally not enabled by default.',
    parameters: EMPTY_UNSAFE_TOOL_PARAMETERS,
    status: 'local-first',
  },
  computer: {
    name: 'computer',
    openaiToolTypes: ['computer'],
    toolModes: ['provider-native', 'adapter-emulated', 'codex-local-first'],
    adapterEmulatedSupported: true,
    providerNativeSupported: true,
    requiresExecutor: true,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_computer',
    description: 'Control a host-provided computer environment through an explicit sandboxed executor.',
    parameters: COMPUTER_TOOL_PARAMETERS,
    status: 'partial',
  },
  code_interpreter: {
    name: 'code_interpreter',
    openaiToolTypes: ['code_interpreter'],
    toolModes: ['provider-native', 'adapter-emulated'],
    adapterEmulatedSupported: true,
    providerNativeSupported: true,
    requiresExecutor: true,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_code_interpreter',
    description: 'Execute code through an explicitly configured sandboxed interpreter provider.',
    parameters: CODE_INTERPRETER_TOOL_PARAMETERS,
    status: 'partial',
  },
  image_generation: {
    name: 'image_generation',
    openaiToolTypes: ['image_generation'],
    toolModes: ['provider-native', 'adapter-emulated'],
    adapterEmulatedSupported: true,
    providerNativeSupported: true,
    requiresExecutor: true,
    unsafeByDefault: false,
    defaultEmulatedToolName: 'adapter_image_generation',
    description: 'Generate images through an explicitly configured adapter image provider.',
    parameters: IMAGE_GENERATION_TOOL_PARAMETERS,
    status: 'partial',
  },
  apply_patch: {
    name: 'apply_patch',
    openaiToolTypes: ['apply_patch'],
    toolModes: ['codex-local-first'],
    adapterEmulatedSupported: false,
    providerNativeSupported: false,
    requiresExecutor: false,
    unsafeByDefault: true,
    defaultEmulatedToolName: 'adapter_apply_patch',
    description: 'Codex custom apply_patch tool. The provider adapter translates/proxies; Codex owns execution.',
    parameters: EMPTY_UNSAFE_TOOL_PARAMETERS,
    status: 'supported',
  },
};

export const CODEX_PROVIDER_BUILTIN_TOOL_ALIASES: Record<string, CodexProviderBuiltinToolName> = {
  web_search: 'web_search',
  file_search: 'file_search',
  tool_search: 'tool_search',
  mcp: 'mcp',
  skill: 'skill',
  shell: 'shell',
  local_shell: 'local_shell',
  computer: 'computer',
  code_interpreter: 'code_interpreter',
  image_generation: 'image_generation',
  apply_patch: 'apply_patch',
};
